repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black

-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c "cd home_inventory && pytest"
        language: system
        verbose: true
        pass_filenames: false
        always_run: true
      - id: footer-commit
        name: add commit date to footer page
        entry: home_inventory/footer-commit.sh
        language: script
