version: "3.8"

services:
  hi-django:
    build:
      context: ./home_inventory
    env_file:
      ./home_inventory/.env
    restart: "on-failure"
    ports:
      - 8000:8000
    networks:
      - nginx_network
      - db_network
    depends_on:
      - hi-postgres

  hi-postgres:
    image: postgres
    restart: "on-failure"
    env_file:
      ./home_inventory/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    networks:
      - db_network

  hi-nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./home_inventory/static:/usr/share/nginx/static
    ports:
      - 8080:80
    networks:
      - nginx_network
    depends_on:
      - hi-django

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  home-inventory: