# Generated by Django 4.0 on 2022-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_category_slugify_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="If True, it's default measurement for new item.Only one measurement can be default.",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="Only one measurement can be default",
            ),
        ),
    ]
